### ISSUE TITLE
Full traceback is sent as bounce message

### ISSUE THREAD

**Issue by tschuettler** [modoboa/modoboa-dmarc#32]
Once an internal error occures, a traceback will be returned to postfix. It will treat non zero return as an error and bounce the mail back to the sender.

However, it will send the full traceback to the sender instead of an error message or just using a SMTP status code.

Legitimate error when a `*.xml.zip`-file was received with content type `application/gzip`:
```
Traceback (most recent call last):
File "/srv/modoboa/instance/manage.py", line 22, in <module> execute_from_command_line(sys.argv)
File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line utility.execute()
File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute self.fetch_command(subcommand).run_from_argv(self.argv)
File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py",  line 283, in run_from_argv self.execute(*args, **cmd_options)
File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute output = self.handle(*args, **options)
File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_dmarc/management/commands/import_aggregated_report.py", line 36, in handle lib.import_report_from_stdin()
File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_dmarc/lib.py", line 159, in import_report_from_stdin import_report_from_email(content)
File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_dmarc/lib.py", line 146, in import_report_from_email import_archive(fpo, content_type=part.get_content_type())
File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_dmarc/lib.py", line 129, in import_archive import_report(zfile.read())
File "/usr/lib/python2.7/gzip.py", line 261, in read self._read(readsize)
File "/usr/lib/python2.7/gzip.py", line 303, in _read self._read_gzip_header()
File "/usr/lib/python2.7/gzip.py", line 197, in _read_gzip_header raise IOError, 'Not a gzipped file' IOError: Not a gzipped file
```

**Comment by kryskool** [comment]
Hi @tschuettler 

Which provider send DMARC report as ZIP file ?

Regards,

**Comment by kryskool** [comment]
Only Gzip allowed on [DMARC](https://tools.ietf.org/html/rfc7489#section-7.2.1.1)

And Gzip is different from ZIP (Mimetype is not the same)

**Comment by tschuettler** [comment]
Hi @kryskool,
it was seznam.cz, and probably just an honest mistake as is it fixed meanwhile.

I agree that it is not according to the specification and the importer should not try to fix that. 

However im uncomfortable with disclosing the full traceback to the sender of the report.
See the DIAGNOSTICS section in http://www.postfix.org/pipe.8.html for handling non-zero exit status codes.

Prehaps a general error handler returning a "5.0.1" instead of any traceback would be more sensible?

**Comment by tschuettler** [comment]
Thanks a lot for the quick implementation @kryskool .

The bounce message is looking great:
```
Action: failed
Status: 5.6.0
Diagnostic-Code: x-unix; Error: the attachment does not match the mimetype
```
