### ISSUE TITLE
No module modoboa_amavis.settings in installation

### ISSUE THREAD

**Issue by Mandrake990** [modoboa/modoboa-dmarc#5]
Hi,

I'm using the version installed with the modoboa_installer.

For now i'm using opendmarc installed by myself and Postfix is connecting to it via opened socket...I want it to be integrated directly inside modoboa interface.

Seems like there's an issue with pip and the installer because i'm trying to setup modoboa_dmarc, but it fails:

-> Added modoboa_dmarc into settings.py as instructions
-> Launching: python manage.py migrate modoboa_dmarc
-> Error:

/srv/modoboa/instance# python manage.py migrate modoboa_dmarc
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/modoboa/instance/instance/settings.py", line 250, in <module>
    from modoboa_amavis.settings import *
ImportError: No module named modoboa_amavis.settings

Seems like it's builded from sources or something like this...

Sorry if i wrote something wrong but i'm not a python/venv expert (i'm using it only for Modoboa)...

Can you please drive me to fix this issue?

Thank you in advance for this fantastic software.

Bob

**Comment by tonioo** [comment]
If you do not plan to use the amavis extension, could you comment the corresponding line within MODOBOA_APPS and retry please ?
